version: "3"
services:
  eureka:
    image: learning-microservices/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka
    ports:
      - "8761:8761"
  customer:
    image: learning-microservices/customer-service:0.0.1-SNAPSHOT
    container_name: customer
    ports:
      - "8081:8081"
    depends_on:
      - eureka
  booking:
    image: learning-microservices/booking-service:0.0.1-SNAPSHOT
    container_name: booking
    ports:
     - "8080:8080"
    depends_on:
      - eureka