apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: customer-service
    tier: backend